import chalk from 'chalk';
import ora from 'ora';
import * as fs from 'fs-extra';
import * as path from 'path';
import { Workflow, WorkflowTemplate } from '../types/workflow.js';
import { getTemplates } from '../templates/index.js';

interface InitOptions {
  template?: string;
  output?: string;
}

/**
 * Initialize a new workflow
 */
export async function initWorkflow(name: string, options: InitOptions): Promise<void> {
  const spinner = ora('Creating workflow...').start();
  
  try {
    let workflow: Workflow;
    
    if (options.template) {
      // Use template
      spinner.text = `Loading template: ${options.template}`;
      const templates = getTemplates();
      const template = templates.find(t => t.id === options.template);
      
      if (!template) {
        spinner.stop();
        console.log(chalk.red(`❌ Template "${options.template}" not found`));
        console.log(chalk.yellow('Run: actionflow templates'));
        return;
      }
      
      workflow = createWorkflowFromTemplate(template, name);
    } else {
      // Create empty workflow
      workflow = createEmptyWorkflow(name);
    }
    
    // Create .github/workflows directory
    const outputDir = path.dirname(options.output || '.github/workflows/workflow.yml');
    await fs.ensureDir(outputDir);
    
    // Export to YAML
    const yaml = await exportToYAML(workflow);
    await fs.writeFile(options.output || '.github/workflows/workflow.yml', yaml);
    
    spinner.stop();
    console.log(chalk.green('✅ Workflow created successfully!'));
    console.log(chalk.cyan(`   📁 ${options.output || '.github/workflows/workflow.yml'}`));
    console.log(chalk.yellow('\n💡 Tip: Run "actionflow edit" to customize'));
    
  } catch (error) {
    spinner.stop();
    throw error;
  }
}

/**
 * Create empty workflow
 */
function createEmptyWorkflow(name: string): Workflow {
  return {
    name,
    on: {
      push: {
        branches: ['main']
      }
    },
    jobs: {}
  };
}

/**
 * Create workflow from template
 */
function createWorkflowFromTemplate(template: WorkflowTemplate, name: string): Workflow {
  return {
    name: name || template.name,
    on: template.on,
    jobs: template.jobs
  };
}

/**
 * Export workflow to YAML
 */
async function exportToYAML(workflow: Workflow): Promise<string> {
  const { dump } = await import('js-yaml');
  
  const yaml = dump(workflow, {
    indent: 2,
    lineWidth: -1, // Don't wrap lines
    noRefs: true
  });
  
  return `# Generated by ActionFlow
# https://github.com/rad1229208927/actionflow

${yaml}`;
}
