/**
 * Generate HTML preview of workflow
 */
export function generateWorkflowHTML(workflow: any): string {
  return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${workflow.name} - ActionFlow Preview</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 40px 20px;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    .header {
      background: white;
      border-radius: 12px;
      padding: 30px;
      margin-bottom: 30px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .header h1 {
      color: #1a202c;
      font-size: 28px;
      margin-bottom: 10px;
    }
    .header p {
      color: #718096;
      font-size: 14px;
    }
    .triggers {
      display: flex;
      gap: 10px;
      margin-top: 20px;
      flex-wrap: wrap;
    }
    .trigger-badge {
      background: #edf2f7;
      color: #4a5568;
      padding: 8px 16px;
      border-radius: 20px;
      font-size: 13px;
      font-weight: 500;
    }
    .job-card {
      background: white;
      border-radius: 12px;
      padding: 25px;
      margin-bottom: 20px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .job-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid #edf2f7;
    }
    .job-title {
      font-size: 20px;
      font-weight: 600;
      color: #2d3748;
    }
    .job-meta {
      display: flex;
      gap: 15px;
      font-size: 13px;
      color: #718096;
    }
    .steps {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .step {
      display: flex;
      align-items: center;
      gap: 15px;
      padding: 15px;
      background: #f7fafc;
      border-radius: 8px;
      border-left: 4px solid #667eea;
    }
    .step-number {
      width: 30px;
      height: 30px;
      background: #667eea;
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 14px;
      flex-shrink: 0;
    }
    .step-content {
      flex: 1;
    }
    .step-name {
      font-weight: 500;
      color: #2d3748;
      margin-bottom: 4px;
    }
    .step-detail {
      font-size: 13px;
      color: #718096;
    }
    .step-type {
      padding: 4px 10px;
      background: #edf2f7;
      border-radius: 12px;
      font-size: 12px;
      color: #4a5568;
      font-weight: 500;
    }
    .arrow {
      text-align: center;
      color: #a0aec0;
      font-size: 20px;
      padding: 10px 0;
    }
    .footer {
      text-align: center;
      color: white;
      margin-top: 40px;
      opacity: 0.8;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🔄 ${workflow.name || 'Workflow'}</h1>
      <p>Generated by ActionFlow - GitHub Actions Visual Builder</p>
      <div class="triggers">
        ${generateTriggerBadges(workflow.on)}
      </div>
    </div>
    
    ${Object.entries(workflow.jobs || {}).map(([jobName, job]: [string, any]) => `
      <div class="job-card">
        <div class="job-header">
          <div class="job-title">⚙️ ${jobName}</div>
          <div class="job-meta">
            <span>🖥️ ${job.runsOn || 'ubuntu-latest'}</span>
            ${job.needs ? `<span>🔗 Needs: ${job.needs.join(', ')}</span>` : ''}
          </div>
        </div>
        <div class="steps">
          ${(job.steps || []).map((step: any, i: number) => `
            ${i > 0 ? '<div class="arrow">⬇️</div>' : ''}
            <div class="step">
              <div class="step-number">${i + 1}</div>
              <div class="step-content">
                <div class="step-name">${step.name || step.uses || step.run || `Step ${i + 1}`}</div>
                <div class="step-detail">
                  ${step.uses ? `Uses: ${step.uses}` : step.run ? `Run: ${step.run}` : 'Action step'}
                </div>
              </div>
              <div class="step-type">${step.uses ? 'Action' : 'Command'}</div>
            </div>
          `).join('')}
        </div>
      </div>
    `).join('')}
    
    <div class="footer">
      Made with 🦞 by ActionFlow
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate trigger badges HTML
 */
function generateTriggerBadges(on: any): string {
  if (!on) return '<span class="trigger-badge">No triggers</span>';
  
  const badges: string[] = [];
  
  if (on.push) badges.push('📤 Push');
  if (on.pull_request) badges.push('🔀 Pull Request');
  if (on.schedule) badges.push('⏰ Schedule');
  if (on.workflow_dispatch) badges.push('👆 Manual');
  if (on.release) badges.push('🏷️ Release');
  
  return badges.map(badge => `<span class="trigger-badge">${badge}</span>`).join('');
}
